version: '3.8'

services:
    pgadmin:
        image: dpage/pgadmin4
        container_name: api_pgadmin
        ports:
            - '5050:80'
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@admin.com
            PGADMIN_DEFAULT_PASSWORD: root
        networks:
            - web_api

    redis:
        image: redis:6.0.9-alpine
        container_name: api_redis
        ports:
            - '6379:6379'
        restart: always
        networks:
            - web_api

    postgesql:
        image: postgres:12-alpine
        container_name: api_postgresql
        ports:
            - '5432:5432'
        restart: always
        environment:
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=secret
            - POSTGRES_DB=SimpleTransaction
        networks:
            - web_api

networks:
    web_api:
        driver: bridge
